import { motion } from 'framer-motion';
import { Card, CardContent } from '@/components/ui/card';
import type { RecapData, CommentaryNote } from '@/types';

interface NotesSlideProps {
    data: RecapData;
}

const categoryEmojis: Record<string, string> = {
    streak: '🔥',
    productivity: '📈',
    languages: '💻',
    social: '🤝',
    repos: '📦',
    general: '✨',
};

const categoryColors: Record<string, string> = {
    streak: 'from-orange-500/10 to-red-500/10 border-orange-500/20',
    productivity: 'from-green-500/10 to-emerald-500/10 border-green-500/20',
    languages: 'from-blue-500/10 to-cyan-500/10 border-blue-500/20',
    social: 'from-pink-500/10 to-purple-500/10 border-pink-500/20',
    repos: 'from-indigo-500/10 to-violet-500/10 border-indigo-500/20',
    general: 'from-primary/10 to-primary/5 border-primary/20',
};

function NoteCard({ note, index }: { note: CommentaryNote; index: number }) {
    const emoji = note.emoji || categoryEmojis[note.category] || '✨';
    const colorClass = categoryColors[note.category] || categoryColors.general;

    return (
        <motion.div
            initial={{ opacity: 0, x: index % 2 === 0 ? -20 : 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: index * 0.15 }}
        >
            <Card className={`bg-gradient-to-br ${colorClass} overflow-hidden`}>
                <CardContent className="p-5">
                    <div className="flex items-start gap-3">
                        <span className="text-2xl">{emoji}</span>
                        <div className="flex-1 min-w-0">
                            <h3 className="font-semibold mb-1">{note.title}</h3>
                            <p className="text-sm text-muted-foreground">{note.content}</p>
                        </div>
                    </div>
                </CardContent>
            </Card>
        </motion.div>
    );
}

export function NotesSlide({ data }: NotesSlideProps) {
    const notes = data.notes.slice(0, 6);

    return (
        <div className="h-full flex flex-col justify-center pt-24 pb-20 px-8">
            {/* Section header */}
            <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-center mb-10"
            >
                <h2 className="text-3xl md:text-4xl font-bold mb-3">Fun Notes</h2>
                <p className="text-muted-foreground text-lg">
                    Personalized observations about your {data.year} journey
                </p>
                <p className="text-xs text-muted-foreground/60 mt-2">
                    Powered by Gemini AI
                </p>
            </motion.div>

            {/* Notes grid */}
            {notes.length > 0 ? (
                <div className="max-w-3xl mx-auto w-full grid grid-cols-1 sm:grid-cols-2 gap-4">
                    {notes.map((note, index) => (
                        <NoteCard key={note.id} note={note} index={index} />
                    ))}
                </div>
            ) : (
                <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="text-center text-muted-foreground"
                >
                    <p>No notes found for this recap; This might be a bug; Please report this</p>
                </motion.div>
            )}

            {/* Disclaimer */}
            <motion.p
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 1 }}
                className="text-center text-xs text-muted-foreground/50 mt-8"
            >
                These insights are generated by AI and are meant for fun
            </motion.p>
        </div>
    );
}
